# Generated by Django 5.2.9 on 2026-01-05 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_setor', models.IntegerField(unique=True, verbose_name='ID Numérico')),
                ('nome', models.CharField(max_length=255)),
                ('email_setor', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_chamado', models.IntegerField(editable=False, null=True, unique=True, verbose_name='ID #')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('impacto_solicitante', models.IntegerField(default=5, verbose_name='Impacto (1-10)')),
                ('confianca_responsavel', models.IntegerField(blank=True, null=True)),
                ('facilidade_responsavel', models.IntegerField(blank=True, null=True)),
                ('ice_score_final', models.FloatField(blank=True, null=True)),
                ('prioridade_label', models.CharField(default='Aguardando Triagem', max_length=50)),
                ('flash', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Em fila', 'Em fila'), ('Em Produção', 'Em Produção'), ('Em Stand By', 'Em Stand By'), ('Fechado', 'Fechado'), ('Declinado', 'Declinado'), ('Evitado', 'Evitado'), ('Repassado', 'Repassado')], default='Em fila', max_length=50)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('prazo_primeira_resposta', models.DateTimeField(blank=True, null=True)),
                ('data_em_producao', models.DateTimeField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('sla_prazo', models.DateTimeField(blank=True, null=True)),
                ('descricao_resposta', models.TextField(blank=True, null=True)),
                ('justificativa_recusa', models.TextField(blank=True, null=True)),
                ('caminhos_anexos', models.JSONField(blank=True, default=dict, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.categoriaconfig')),
                ('responsavel_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='tickets.colaborador')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='tickets.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='categoriaconfig',
            name='setor_dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.setor'),
        ),
    ]
