# Generated by Django 5.2.9 on 2026-01-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='setor_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_recebidos', to='tickets.setor'),
        ),
    ]
