# Generated by Django 5.2.9 on 2026-01-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_chamado_setor_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='prazo_primeira_resposta',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='prioridade_label',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='setor_destino',
        ),
        migrations.AddField(
            model_name='categoriaconfig',
            name='sla_padrao_horas',
            field=models.IntegerField(default=24, help_text='SLA padrão em horas'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_inicio_standby',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='setor_destino_cache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.setor'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='categorias_atribuidas',
            field=models.ManyToManyField(blank=True, related_name='resolutores', to='tickets.categoriaconfig', verbose_name='Permissão para atender:'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='É Head/Gestor?'),
        ),
        migrations.AddField(
            model_name='setor',
            name='is_gestor',
            field=models.BooleanField(default=False, verbose_name='É setor de Gestão?'),
        ),
        migrations.AlterField(
            model_name='categoriaconfig',
            name='setor_dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cats_antigas', to='tickets.setor'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_chamado',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='impacto_solicitante',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='responsavel_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.colaborador'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Em fila', 'Em fila'), ('Em Produção', 'Em Produção'), ('Stand By', 'Stand By'), ('Homologação', 'Homologação'), ('Fechado', 'Fechado'), ('Declinado', 'Declinado'), ('Evitado', 'Evitado'), ('Cancelado', 'Cancelado')], default='Em fila', max_length=50),
        ),
        migrations.CreateModel(
            name='Subsetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('setor_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsetores', to='tickets.setor')),
            ],
        ),
        migrations.AddField(
            model_name='categoriaconfig',
            name='subsetor_pertencente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tickets.subsetor'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='subsetor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.subsetor'),
        ),
    ]
