# Generated by Django 5.2.9 on 2026-01-06 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_chamado_prazo_primeira_resposta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaconfig',
            name='setor_dono',
        ),
        migrations.AddField(
            model_name='chamado',
            name='prazo_resposta_inicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo 1ª Resposta'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tempo_total_standby',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='categoriaconfig',
            name='subsetor_pertencente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tickets.subsetor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='confianca_responsavel',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='facilidade_responsavel',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='ice_score_final',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_chamado',
            field=models.IntegerField(editable=False, null=True, unique=True, verbose_name='ID #'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='impacto_solicitante',
            field=models.IntegerField(default=5, help_text='1-10'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='responsavel_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='tickets.colaborador'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='sla_prazo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA Resolução'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='categorias_atribuidas',
            field=models.ManyToManyField(blank=True, related_name='resolutores', to='tickets.categoriaconfig'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='É Gestor?'),
        ),
    ]
