# Generated by Django 5.2.9 on 2026-01-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_categoriaconfig_setor_dono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='flag_editado',
            field=models.BooleanField(default=False, verbose_name='Foi editado?'),
        ),
    ]
